branch-defaults:
  master:
    environment: cognitiveServer-prd-env
environment-defaults:
  cognitiveServer-prd-env:
    branch: null
    repository: null
global:
  application_name: Cognitive Server
  default_ec2_keyname: mustafa
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Tomcat 8 with Java
    8 running on 64bit Amazon Linux/2.7.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/my-app-1.0-SNAPSHOT.war

